[package]
name = "xde"
version = "0.1.0"
authors = [
    "Ryan Goodfellow <ryan.goodfellow@oxide.computer>",
    "Ryan Zezeski <ryan@oxide.computer>"
]
# XXX convert to 2021
edition = "2018"

[dependencies]
bitflags = "1.3.2"
#
# XXX It looks like alloc::ffi::CString might be a thing soon.
#
# https://github.com/rust-lang/rust/pull/94079
#
cstr_core = { version = "0.2.4", default-features = false }
illumos-sys-hdrs = { path = "../illumos-sys-hdrs", features = ["kernel"] }
postcard = { version = "0.7.0", features = ["alloc"], default-features = false }

[dependencies.opte]
path = "../opte"
default-features = false
features = ["engine", "kernel"]

[dependencies.oxide-vpc]
path = "../oxide-vpc"
default-features = false
features = ["engine", "kernel"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["alloc", "derive"]

[lib]
crate-type = ["staticlib"]
name = "xde"

# Some of these values are the same as the defaults, but it helps to
# be explicit sometimes.
[profile.dev]
codegen-units = 1
debug = 2
incremental = false
opt-level = 0
panic = 'abort'

[profile.release]
codegen-units = 1
debug = 2
incremental = false
panic = 'abort'
